token:
  expiration_time: 864000000
  secret: token

spring:
  application:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 1234
gateway:
  ip: 127.0.0.1
